### PR TITLE
MNT: Re-rendered with conda-smithy 3.1.8 and pinning 2018.07.24

### PR DESCRIPTION
**Pull request by weaverba137**
Rerender existing version with conda-smithy > 3.

### CODE REVIEW

**Comment by weaverba137** [comment]
@mwcraig, @bsipocz, does Astropy currently have a recommendation as to installing with pip versus `python setup.py install`?

**Comment by mwcraig** [comment]
If pydl uses astropy helpers then stick with setup.py for now...helpers tries to auto update during install

**Comment by weaverba137** [comment]
@mwcraig, indeed it does.  Thank you!

**Comment by weaverba137** [comment]
PS, I need to bump the build number, but I want to make sure all tests are working, so this isn't quite ready to merge yet.

**Pull request merged**
